# Generated by Django 4.0.3 on 2022-04-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0002_reservation_customer_name_reservation_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.reservation')),
            ],
        ),
    ]
