# Generated by Django 4.0.3 on 2022-04-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0004_remove_guestdetails_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetails',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='guestdetails',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.reservation'),
        ),
    ]
