# Generated by Django 4.0.3 on 2022-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0005_remove_guestdetails_reservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(default=250),
        ),
    ]
