# Generated by Django 4.0.3 on 2022-04-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0006_hotel_availability_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='gender',
            field=models.CharField(default='male', max_length=100),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
